print("Learning about you")

YourName = input("What is your name?")
Hungry = input ("What is your favorite food?")
Music = input("What is your favorite music?")
WhereAreYou = input("Where are you")
print("You are")
print(YourName)
print() 
print("You're probably hungry for taco")
print(Hungry)
print()
print("You're probably listening to kanye")
print (Music)
print()
print ("You're probably living in the amazing new york city")
print (WhereAreYou)
print() 
print ("Have a tubular day!")
